name: "Configuration E-commerce Complète"
description: "Configuration complète pour un système e-commerce avec règles métier, ontologie et paramètres"
version: "1.0.0"
created_at: "2024-01-15T10:30:00Z"
updated_at: "2024-01-15T10:30:00Z"

rule_engine:
  business_rules:
    - name: "Règle Commande Express"
      description: "Gestion des commandes express avec livraison prioritaire"
      conditions:
        intent: "commander"
        delivery_type: "express"
        amount:
          operator: ">="
          value: 50
      actions:
        - action: "check_stock"
          params:
            product_id: "{product_id}"
        - action: "process_payment"
          params:
            amount: "{amount}"
        - action: "schedule_delivery"
          params:
            type: "express"
      priority: 1
      category: "commande"
      enabled: true
      created_at: "2024-01-15T10:30:00Z"

    - name: "Règle Remise Fidélité"
      description: "Application de remise pour clients fidèles"
      conditions:
        intent: "commander"
        customer_type: "fidèle"
        amount:
          operator: ">="
          value: 100
      actions:
        - action: "apply_discount"
          params:
            percentage: 10
        - action: "process_payment"
          params:
            amount: "{amount_with_discount}"
      priority: 2
      category: "fidélité"
      enabled: true
      created_at: "2024-01-15T10:30:00Z"

    - name: "Règle Vérification Stock"
      description: "Vérification automatique du stock avant commande"
      conditions:
        intent: "commander"
      actions:
        - action: "check_stock"
          params:
            product_id: "{product_id}"
        - action: "notify_stock_status"
          params:
            customer_id: "{customer_id}"
      priority: 3
      category: "stock"
      enabled: true
      created_at: "2024-01-15T10:30:00Z"

    - name: "Règle Livraison Gratuite"
      description: "Livraison gratuite pour commandes supérieures à 100€"
      conditions:
        intent: "commander"
        amount:
          operator: ">="
          value: 100
      actions:
        - action: "apply_free_shipping"
          params:
            order_id: "{order_id}"
        - action: "notify_free_shipping"
          params:
            customer_id: "{customer_id}"
      priority: 4
      category: "livraison"
      enabled: true
      created_at: "2024-01-15T10:30:00Z"

  statistics:
    total_rules: 4
    active_rules: 4
    rules_by_category:
      commande: 1
      fidélité: 1
      stock: 1
      livraison: 1

  templates:
    commande_template:
      conditions:
        intent: "commander"
      actions:
        - action: "check_stock"
        - action: "process_payment"
        - action: "schedule_delivery"

knowledge_base:
  ontology_classes:
    - name: "Product"
      properties:
        - "name"
        - "price"
        - "stock"
        - "category"
        - "description"
        - "brand"
        - "sku"
      description: "Entité représentant un produit"
      uri: "http://example.com/ontology#Product"

    - name: "Order"
      properties:
        - "order_id"
        - "customer_id"
        - "items"
        - "total"
        - "status"
        - "created_at"
        - "delivery_address"
      description: "Entité représentant une commande"
      uri: "http://example.com/ontology#Order"

    - name: "Customer"
      properties:
        - "customer_id"
        - "name"
        - "email"
        - "phone"
        - "address"
        - "loyalty_points"
        - "customer_type"
      description: "Entité représentant un client"
      uri: "http://example.com/ontology#Customer"

    - name: "Category"
      properties:
        - "category_id"
        - "name"
        - "description"
        - "parent_category"
        - "image_url"
      description: "Entité représentant une catégorie de produits"
      uri: "http://example.com/ontology#Category"

  instances: []
  business_handlers:
    - name: "ProductHandler"
      description: "Gestionnaire pour les produits"
      methods:
        - "create_product"
        - "update_stock"
        - "get_product_info"
    - name: "OrderHandler"
      description: "Gestionnaire pour les commandes"
      methods:
        - "create_order"
        - "update_order_status"
        - "calculate_total"

vector_store:
  collections:
    - name: "products"
      description: "Collection des produits"
      vector_count: 0
    - name: "orders"
      description: "Collection des commandes"
      vector_count: 0
    - name: "customers"
      description: "Collection des clients"
      vector_count: 0
  statistics:
    total_vectors: 0
    collections_count: 3

llm_config:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000
  api_key_configured: true
  system_prompt: "Vous êtes un assistant spécialisé dans la gestion de commandes e-commerce. Vous pouvez traiter les demandes de commande, vérifier le stock, et gérer les paiements."

tools_config:
  stock_api:
    enabled: true
    endpoint: "http://localhost:5001/api/tools/stock"
    timeout: 30
    retry_count: 3
  payment_api:
    enabled: true
    endpoint: "http://localhost:5001/api/tools/payment"
    timeout: 60
    retry_count: 3
  delivery_api:
    enabled: true
    endpoint: "http://localhost:5001/api/tools/delivery"
    timeout: 45
    retry_count: 2
  notification_api:
    enabled: true
    endpoint: "http://localhost:5001/api/tools/notification"
    timeout: 30
    retry_count: 2

agent_config:
  intent_patterns:
    commander:
      - "commander"
      - "acheter"
      - "passer commande"
      - "je veux commander"
      - "ajouter au panier"
    consulter:
      - "consulter"
      - "voir"
      - "afficher"
      - "montrer"
      - "rechercher"
    annuler:
      - "annuler"
      - "supprimer"
      - "retirer"
      - "annuler commande"
    livraison:
      - "livraison"
      - "expédition"
      - "délai"
      - "suivi"
  fallback_enabled: true
  confidence_threshold: 0.7
  max_actions_per_query: 5
  response_timeout: 30

metadata:
  exported_by: "ConfigurationManager"
  system_version: "1.0.0"
  business_domain: "e-commerce"
  tags:
    - "e-commerce"
    - "commande"
    - "livraison"
    - "paiement"
  notes: "Configuration optimisée pour un site e-commerce avec gestion complète des commandes" 